### ISSUE TITLE
ApigeeAPSDestination / destinationAllDevices issue 

### ISSUE THREAD

**Issue by jwest-apigee** [apigee/apigee-ios-sdk#114]
The push sample operation for 'all devices' does not seem to work.  It looks like https://github.com/apigee/apigee-ios-sdk/blob/master/source/Classes/AppServices/ApigeeAPSDestination.m#L53 should change

From:
    destination.deliveryPath = @"devices;ql=*";
To:
    destination.deliveryPath = @"devices/*";

I have tested it and it seems to work...

**Comment by RobertWalsh** [comment]
Interesting find here.  Will look into it and try your fix and get back to you.
