### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by usmanf** [apigee/apigee-ios-sdk#119]
I am getting the following errors when I run the script (I am using Xcode 7.2)

bash-3.2$ ./Scripts/framework.sh

apigee-ios-sdk-2.0.16/source/Classes/CrashReporter/ApigeePLCrashAsyncLinkedList.hpp:53:1: error: 
templates must have C++ linkage
template <typename V>

apigee-ios-sdk-2.0.16/source/Classes/CrashReporter/ApigeePLCrashAsyncLinkedList.hpp:170:23: error: unknown type name 'async_list'
template <typename V> async_list<V>::async_list (void) {

apigee-ios-sdk-2.0.16/source/Classes/CrashReporter/ApigeePLCrashAsyncLinkedList.hpp:170:33: error: expected unqualified-id
template <typename V> async_list<V>::async_list (void) {

**Comment by RobertWalsh** [comment]
This has been fixed.  Looks like you are running an older version of the SDK.  Please download the latest source directly from Github.

**Comment by usmanf** [comment]
Thanks. Apigee referes to old sdk in their documentation on the their site.
