### ISSUE TITLE
Unable to integrate apigee throught pod in xcode 7.3

### ISSUE THREAD

**Issue by mcaritesh** [apigee/apigee-ios-sdk#120]
Hi 

We are using this library since more than 2 years its really good library. Now i upgared with the new xcode 7.3 and trying to use this through pod file. And use the pod update command to update the all pod dependencies. But all other dependencies is working fine only apigee is showing some error. I attached the errors on the bottom. Please help us. Thanks.

ERROR LOG:
----------------------------------

 [!] /bin/bash -c 
set -e
./build_release_zip.sh 2.0.17

Build settings from command line:
    SDKROOT = iphoneos9.3

=== CLEAN TARGET ApigeeiOSSDK OF PROJECT ApigeeiOSSDK WITH CONFIGURATION Release ===

Check dependencies

**Comment by RobertWalsh** [comment]
I have updated to version 2.0.18 on Github and Cocoapods that fixes this issue.
